language: node_js
node_js: node
env:
- NODE_ENV=production
script: npm run release
deploy:
- provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: dist
- provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: dist/*
  on:
    tags: true
